// Mocks generated by Mockito 5.3.2 from annotations
// in drink_it/test/core/features/cocktail/usecases/search_by_ingredient_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:drink_it/core/features/cocktail/datasources/cocktail_external_datasource.dart'
    as _i5;
import 'package:drink_it/core/features/cocktail/datasources/cocktail_local_datasource.dart'
    as _i2;
import 'package:drink_it/core/features/cocktail/models/cocktail_item_model.dart'
    as _i4;
import 'package:drink_it/core/utils/network_info.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CocktailLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCocktailLocalDatasource extends _i1.Mock
    implements _i2.CocktailLocalDatasource {
  MockCocktailLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CocktailItem>> getCocktails({
    String? ingredient,
    String? category,
    String? alcoholic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCocktails,
          [],
          {
            #ingredient: ingredient,
            #category: category,
            #alcoholic: alcoholic,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.CocktailItem>>.value(<_i4.CocktailItem>[]),
      ) as _i3.Future<List<_i4.CocktailItem>>);
}

/// A class which mocks [CocktailExternalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCocktailExternalDatasource extends _i1.Mock
    implements _i5.CocktailExternalDatasource {
  MockCocktailExternalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CocktailItem>> getCocktails({
    String? ingredient,
    String? category,
    String? alcoholic,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCocktails,
          [],
          {
            #ingredient: ingredient,
            #category: category,
            #alcoholic: alcoholic,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.CocktailItem>>.value(<_i4.CocktailItem>[]),
      ) as _i3.Future<List<_i4.CocktailItem>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
