final cocktailsColumns = [
  "idDrink",
  "strDrink",
  "strTags",
  "strVideo",
  "strCategory",
  "strAlcoholic",
  "strGlass",
  "strInstructions",
  "strInstructionsES",
  "strInstructionsDE",
  "strInstructionsFR",
  "strInstructionsIT",
  "strDrinkThumb",
  "strIngredient1",
  "strIngredient2",
  "strIngredient3",
  "strIngredient4",
  "strIngredient5",
  "strIngredient6",
  "strIngredient7",
  "strIngredient8",
  "strIngredient9",
  "strIngredient10",
  "strIngredient11",
  "strIngredient12",
  "strIngredient13",
  "strIngredient14",
  "strIngredient15",
  "strMeasure1",
  "strMeasure2",
  "strMeasure3",
  "strMeasure4",
  "strMeasure5",
  "strMeasure6",
  "strMeasure7",
  "strMeasure8",
  "strMeasure9",
  "strMeasure10",
  "strMeasure11",
  "strMeasure12",
  "strMeasure13",
  "strMeasure14",
  "strMeasure15",
  "dateModified",
];

const cocktailsTable = """
  CREATE TABLE cocktails(
    idDrink TEXT UNIQUE,
    strDrink TEXT,
    strTags TEXT,
    strVideo TEXT,
    strCategory TEXT,
    strIBA TEXT,
    strAlcoholic TEXT,
    strGlass TEXT,
    strInstructions TEXT,
    strInstructionsES TEXT,
    strInstructionsDE TEXT,
    strInstructionsFR TEXT,
    strInstructionsIT TEXT,
    strInstructionsZH-HANS TEXT,
    strInstructionsZH-HANT TEXT,
    strDrinkThumb TEXT,
    strIngredient1 TEXT,
    strIngredient2 TEXT,
    strIngredient3 TEXT,
    strIngredient4 TEXT,
    strIngredient5 TEXT,
    strIngredient6 TEXT,
    strIngredient7 TEXT,
    strIngredient8 TEXT,
    strIngredient9 TEXT,
    strIngredient10 TEXT,
    strIngredient11 TEXT,
    strIngredient12 TEXT,
    strIngredient13 TEXT,
    strIngredient14 TEXT,
    strIngredient15 TEXT,
    strMeasure1 TEXT,
    strMeasure2 TEXT,
    strMeasure3 TEXT,
    strMeasure4 TEXT,
    strMeasure5 TEXT,
    strMeasure6 TEXT,
    strMeasure7 TEXT,
    strMeasure8 TEXT,
    strMeasure9 TEXT,
    strMeasure10 TEXT,
    strMeasure11 TEXT,
    strMeasure12 TEXT,
    strMeasure13 TEXT,
    strMeasure14 TEXT,
    strMeasure15 TEXT,
    strImageSource TEXT,
    strImageAttribution TEXT,
    strCreativeCommonsConfirmed TEXT,
    dateModified TEXT,
  );
""";
